# this is an example configuration file for the db2 exporter
# it defines the exporter port, database connections, and queries to run
# create your own "myconfig.yaml" based on this template

exporter_port: 8000

databases:
  - host: 192.168.2.1
    port: 50000
    database: SAMPLE1
    user: myuser
    password: mypassword

  - host: db2host2
    port: 50001
    database: SAMPLE2
    user: db2inst1
    password: secret2

queries:
  - name: "database_metrics"
    query: "SELECT * FROM TABLE(MON_GET_DATABASE(-2)) AS t"
    metric_origin: "mongetdatabase"
    gauge_metrics:
      - MEMBER
      - DB_STATUS
      - DB_ACTIVATION_STATE
      - DB_CONN_TIME
      - CATALOG_PARTITION
      - LAST_BACKUP
      - CONNECTIONS_TOP
      - APPLS_CUR_CONS
      - APPLS_IN_DB2
      - NUM_ASSOC_AGENTS
      - AGENTS_TOP
      - NUM_COORD_AGENTS
      - COORD_AGENTS_TOP
      - NUM_LOCKS_HELD
      - NUM_LOCKS_WAITING
      - LOCK_LIST_IN_USE
      - ACTIVE_SORTS
      - ACTIVE_HASH_JOINS
      - ACTIVE_OLAP_FUNCS
      - DB_PATH
      - NUM_POOLED_AGENTS
      - ACTIVE_HASH_GRPBYS
      - SORT_SHRHEAP_TOP
      - ACTIVE_HASH_GRPBYS_TOP
      - ACTIVE_HASH_JOINS_TOP
      - ACTIVE_OLAP_FUNCS_TOP
      - ACTIVE_PEAS
      - ACTIVE_PEAS_TOP
      - ACTIVE_PEDS
      - ACTIVE_PEDS_TOP
      - ACTIVE_SORT_CONSUMERS
      - ACTIVE_SORT_CONSUMERS_TOP
      - ACTIVE_SORTS_TOP
      - ACTIVE_COL_VECTOR_CONSUMERS
      - ACTIVE_COL_VECTOR_CONSUMERS_TOP
      - SORT_CONSUMER_HEAP_TOP
      - SORT_CONSUMER_SHRHEAP_TOP
      - SORT_HEAP_TOP
      - TOTAL_BACKUPS
      - SHR_WORKSPACE_ACTIVE
      - SHR_WORKSPACE_INACTIVE
      - AUTHN_CACHE_MEMORY_USAGE
    extra_labels:
      - member

  - name: "another_metric_set"
    metric_origin: "mongetbufferpool"
    query: "SELECT * FROM TABLE(MON_GET_BUFFERPOOL('',-2)) AS t"
    gauge_metrics:
      - bufferpool_hits
    extra_labels:
      - bp_name
      - member

  - name: "transactionlog_metrics"
    metric_origin: "mongettransactionlog"
    query: "SELECT * FROM TABLE(MON_GET_transaction_log(-2)) AS t"
    extra_labels:
      - member

  - name: "envgetsystemresources"
    metric_origin: "envgetsystemresources"
    query: "SELECT * FROM TABLE(ENV_GET_SYSTEM_RESOURCES()) AS t"
    extra_labels:
      - member
      - HOST_NAME
      

  - name: "idug metric"
    metric_origin: "mongetconnection"
    query: "SELECT * FROM TABLE(MON_GET_CONNECTION(NULL,-2)) AS t"
#    gauge_metrics:
#      - CONNECTION_REUSABILITY_STATUS
    extra_labels:
      - application_name
      - application_handle
      - application_id
      #- CLIENT_WRKSTNNAME
      #- CLIENT_ACCTNG
      #- CLIENT_USERID
      #- CLIENT_APPLNAME
      #- CLIENT_PID
      #- CLIENT_PRDID
      #- CLIENT_PLATFORM
      #- CLIENT_PROTOCOL
      #- SYSTEM_AUTH_ID
      #- SESSION_AUTH_ID
      #- CLIENT_HOSTNAME
      #- CLIENT_IPADDR
      #- TENANT_NAME
      #- TENANT_ID
      - member
      # - WORKLOAD_OCCURRENCE_STATE
      # - LAST_EXECUTABLE_ID
      # - LAST_REQUEST_TYPE
      # - INTRA_PARALLEL_STATE
      # - CURRENT_ISOLATION
      # - UOW_COMP_STATUS
      # - EXECUTION_ID
      # - REUSABILITY_STATUS_REASON
      # - SESSION_PRIORITY
      # - CONNECT_SEC_TYPE
      # - CONNECT_CIPHER_SPEC
      # - SSL_SRV_CERT_LABEL
      # - SSL_SRV_CERT_FINGERPRINT