{
 "title": "Db2 Workload",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "query0" },
   {
    "name": "query1",
    "query": {
     "query": "label_values(db2_mongetdatabase_act_aborted_total,database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TRX Log Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(db2_mongettransactionlog_total_log_used_total{database=\"$query1\"})\n/\n(\n    avg(db2_mongettransactionlog_total_log_used_total{database=\"$query1\"})\n    +\n    avg(db2_mongettransactionlog_total_log_available_total{database=\"$query1\"})\n)",
     "legendFormat": "TRX Log Used PCT"
    }
   ]
  },
  {
   "title": "Lock Wait per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(db2_mongetdatabase_lock_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "lock_wait_time"
    }
   ]
  },
  {
   "title": "Applications Executing PCT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(db2_mongetdatabase_appls_in_db2{database=\"$query1\"})\n/\navg(db2_mongetdatabase_appls_cur_cons{database=\"$query1\"})",
     "legendFormat": "Apps Connected"
    }
   ]
  },
  {
   "title": "CPU usage Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db2_envgetsystemresources_cpu_usage_total{database=\"$query1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dyn STMT per sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(db2_mongetdatabase_dynamic_sql_stmts_total{database=\"$query1\"}[$__rate_interval]))\n",
     "legendFormat": "Dynamic Statements"
    }
   ]
  },
  {
   "title": "Static STMT  per sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(db2_mongetdatabase_static_sql_stmts_total{database=\"$query1\"}[$__rate_interval]))",
     "legendFormat": "Static Statements"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(db2_mongetdatabase_appls_cur_cons{database=\"$query1\"})",
     "legendFormat": "Apps Connected"
    },
    {
     "expr": "avg(db2_mongetdatabase_appls_in_db2{database=\"$query1\"})",
     "legendFormat": "Apps Executing"
    }
   ]
  },
  {
   "title": "Workload per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(db2_mongetdatabase_rows_read_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "rows read"
    },
    {
     "expr": "rate(db2_mongetdatabase_rows_modified_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "rows modified"
    },
    {
     "expr": "rate(db2_mongetdatabase_rows_returned_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "rows returned"
    },
    {
     "expr": "rate(db2_mongetdatabase_pool_data_l_reads_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "pool_data_l_reads"
    },
    {
     "expr": "rate(db2_mongetdatabase_pool_data_p_reads_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "pool_data_p_reads"
    },
    {
     "expr": "rate(db2_mongetdatabase_pool_data_writes_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "pool_data_writes"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_app_commits_total{database=\"$query1\"}[$__rate_interval])\n+\nrate(db2_mongetdatabase_total_app_rollbacks_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "transactions"
    },
    {
     "expr": "rate(db2_mongetdatabase_direct_reads_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "direct reads"
    },
    {
     "expr": "rate(db2_mongetdatabase_direct_writes_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "direct writes"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg(db2_mongetdatabase_appls_cur_cons{database=\"$query1\"})",
     "legendFormat": "Apps Connected"
    },
    {
     "expr": "avg(db2_mongetdatabase_appls_in_db2{database=\"$query1\"})",
     "legendFormat": "Apps Executing"
    }
   ]
  },
  {
   "title": "Request Time Distribution per second (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(db2_mongetdatabase_total_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_compile_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_compile_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_implicit_compile_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_implicit_compile_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_routine_user_code_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_routine_user_code_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_section_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_section_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_commit_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_commit_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_rollback_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_rollback_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_reorg_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_reorg_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_load_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_load_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_backup_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_backup_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_index_build_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_index_build_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_connect_request_proc_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_connect_request_proc_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_rqst_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_rqst_time"
    }
   ]
  },
  {
   "title": "Request Time Distribution Mean",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Wait Time Distribution per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(db2_mongetdatabase_total_cpu_time_total{database=\"$query1\"}[$__rate_interval])/1000    ",
     "legendFormat": "total_cpu_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_pool_read_time_total{database=\"$query1\"}[$__rate_interval])\n+\nrate(db2_mongetdatabase_pool_write_time_total{database=\"$query1\"}[$__rate_interval])\n+\nrate(db2_mongetdatabase_direct_read_time_total{database=\"$query1\"}[$__rate_interval])\n+\nrate(db2_mongetdatabase_direct_write_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "IO Time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_section_sort_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_section_sort_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_lock_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "lock_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_log_disk_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "log_disk_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_extended_latch_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_extended_latch_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_wlm_queue_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "wlm_queue_time_total"
    },
    {
     "expr": "rate(db2_mongetdatabase_log_buffer_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "log_buffer_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_evmon_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "evmon_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_prefetch_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "prefetch_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_comm_exit_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "comm_exit_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_agent_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "agent_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_tcpip_recv_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "tcpip_recv_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_tcpip_send_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "tcpip_send_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_disp_run_queue_time_total{database=\"$query1\"}[$__rate_interval])/1000",
     "legendFormat": "total_disp_run_queue_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_ipc_recv_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "ipc_recv_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_ipc_send_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "ipc_send_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_fcm_send_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "fcm_send_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_fcm_recv_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "fcm_recv_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_audit_subsystem_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "audit_subsystem_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_audit_file_write_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "audit_file_write_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_diaglog_write_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "diaglog_write_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_ida_send_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "ida_send_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_ida_recv_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "ida_recv_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_cf_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "cf_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_reclaim_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "reclaim_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_spacemappage_reclaim_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "spacemappage_reclaim_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_ext_table_recv_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "ext_table_recv_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_ext_table_send_wait_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "ext_table_send_wait_time"
    },
    {
     "expr": "rate(db2_mongetdatabase_total_rqst_time_total{database=\"$query1\"}[$__rate_interval])",
     "legendFormat": "total_rqst_time"
    }
   ]
  },
  {
   "title": "Wait Time Distribution Mean",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  }
 ]
}